version: "3"

services:
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=development
    environment:
      - PORT=3001
      - MONGO_USER=admin
      - MONGO_PASS=admin
      - MONGO_DB=mern
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn dev

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile.dev
  #     args:
  #       - SERVER_URL=http://localhost:3001/api/v1
  #   stdin_open: true
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./web:/app
  #     - /app/node_modules
  #   command: yarn dev
