version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

  server:
    build: ./server
    # image: higoreduardodocs/swarm
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
    driver: local
