version: "3"

services:
  nginx:
    container_name: nginx
    ports:
      - 3000:80

  server:
    build:
      context: ./server
      args:
        - NODE_ENV=development
    container_name: server
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASS=admin
      - MONGO_DB=swarm
    # ports:
    #   - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn dev

  mongo:
    container_name: mongo
