version: "3"

services:
  server:
    build: ./server
    # image: higoreduardodocs/docker-mern-server
    container_name: server
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always
    volumes:
      - mongo-db:/data/db

  # web:
  #   image: higoreduardodocs/docker-mern-web
  #   container_name: web

volumes:
  mongo-db:
    driver: local
