@server=http://localhost:3000/api/v1

@users=users

### POST /sign-up
POST {{ server }}/{{ users }}/sign-up HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}

### POST /sign-up
POST {{ server }}/{{ users }}/sign-in HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}

@posts=posts
@postId=661d24fa00d3d14096238449

### POST /
POST {{ server }}/{{ posts }} HTTP/1.1
Content-Type: application/json

{
  "title": "Título",
  "body": "Corpo"
}

### GET /
GET {{ server }}/{{ posts }} HTTP/1.1

### PATCH /:id
PATCH {{ server }}/{{ posts }}/{{ postId }} HTTP/1.1
Content-Type: application/json

{
  "title": "Título 2"
}

### GET /:id
GET {{ server }}/{{ posts }}/{{ postId }} HTTP/1.1

### DELETE /:id
DELETE {{ server }}/{{ posts }}/{{ postId }} HTTP/1.1